### ISSUE TITLE
Quality control

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fusioninventory-ios#12]
- [x] Swift Style Guide
- [x] Check if the Podspec lints correctly.
This can be done with two methods, `pod lib lint` and `pod spec lint`. 
- [x] Unit Testing
- [x] Integrate Travis CI for these tests

**Comment by hectorerb** [comment]
We use this swift style guide 

https://github.com/raywenderlich/swift-style-guide

**Comment by ajsb85** [comment]
SwiftLint
https://github.com/realm/SwiftLint

**Comment by hectorerb** [comment]
Xcode integrates a tool to analyze the code
https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/static_analyzer.html
