### ISSUE TITLE
What type of accounts we required to implement MDM?

### ISSUE THREAD

**Issue by Lyankar** [flyve-mdm/fusioninventory-ios#159]
Hai, this is Lyankar. To implement MDM what type accounts we required, which means prerequisites. Actually some other MDM's requires Apple Enterprise account, Apple Developer account and Apple DEP etc. So please explain. 

And please provide if any tutorials available to implement Flyve-MDM.

**Comment by hectorerb** [comment]
Hi, @Lyankar thanks for considering using Flyve MDM, at the moment we are in the MDM server development phase for iOS.

The prerequisites you have already mentioned, additionally we integrate [glpi](https://github.com/glpi-project/glpi) and [fusion Inventory](http://fusioninventory.org)

I invite you to review this repo, it allows you to get hardware and software inventory of your iOS devices

**Comment by Naylin15** [comment]
Hi @Lyankar 

For more information you can also visit our project site [iOS Inventory Agent](http://flyve.org/ios-inventory-agent/howtos/)

**Comment by Lyankar** [comment]
@hectorerb, thank you very much. Apple Enterprise account, Apple Developer account and Apple DEP  are mandatory or not, can you please clarify it?. Because we don't have DEP and Apple Enterprise account. We have only Apple developer account. Is it enough to implement Flyve-MDM?. We have 250+ iPads to implement MDM.

**Comment by ajsb85** [comment]
Hi, @Lyankar
This inventory agent include basic features of the MDM. You just need to install this app from TestFlight (beta) or the Apple Store of iOS.
This agent report hardware information, hardware usage and status of the device, network services, etc.
The full features for the MDM are coming in the next weeks.
Send me an email to keep in touch.
asalas@teclib.com

**Comment by Lyankar** [comment]
@ajsb85, thank you very much....

**Comment by ajsb85** [comment]
Hi, @Lyankar 
Some updates of features coming soon.
If you deploy Flyve MDM in your servers or in a cloud computing service like Azure or AWS you needs to enroll to the Apple Enterprise subscription and request the MDM features.
If you use our subscriptions plans, you don't need to enroll to the Apple Enterprise.

**Comment by scubess** [comment]
> Hi @Lyankar
> 
> For more information you can also visit our project site [iOS Inventory Agent](http://flyve.org/ios-inventory-agent/howtos/> Hi, @Lyankar
> This inventory agent include basic features of the MDM. You just need to install this app from TestFlight (beta) or the Apple Store of iOS.
> This agent report hardware information, hardware usage and status of the device, network services, etc.
> The full features for the MDM are coming in the next weeks.
> Send me an email to keep in touch.
> [asalas@teclib.com](mailto:asalas@teclib.com)

Hi, The link for app inventory agent is broken 
[iOS inventory Agent](https://itunes.apple.com/us/app/inventory-agent/id1261412260).. Where i can find beta release or working url for inventory agent please ?
