### ISSUE TITLE
Rename Bundle ID & SKU

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fusioninventory-ios#27]
## Bundle ID

The bundle ID must match the one you used in Xcode. It can't be changed after you upload your first build.

**Actual**: org.flyve.inventory.agent.example
**New**: org.flyve.inventory.agent

## SKU

A unique ID for your app that is not visible on the App Store.

**Actual**: FlyveMDMiOSInventoryAgentExample
**New**:  FlyveMDMInventoryAgent

**Comment by hectorerb** [comment]
@ajsb85 We already have an apple account?

**Comment by hectorerb** [comment]
Ref: https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/commit/8b6f4bda81b8901bd2368223be23086c391d12e3
