### ISSUE TITLE
Auto increment build number when upload app to TestFlight

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/fusioninventory-ios#33]
TRAVIS_BUILD_NUMBER
https://docs.travis-ci.com/user/environment-variables/

**Comment by ajsb85** [comment]
`scripts/update-bundle.sh`
https://github.com/MattesGroeger/TravisExample-iOS/blob/master/scripts/update-bundle.sh

**Comment by ajsb85** [comment]
A sensible way to increment bundle version (CFBundleVersion) in Xcode
http://tgoode.com/2014/06/05/sensible-way-increment-bundle-version-cfbundleversion-xcode/
