### ISSUE TITLE
Use iTunes Connect API with Spaceship

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/fusioninventory-ios#47]
Hi, @ajsb85

Change connect to iTunes Connect API from fastlane tools to spaceship

https://github.com/fastlane/fastlane/tree/master/spaceship

**Comment by ajsb85** [comment]
Hi, @hectorerb 
I think this issue is already completed.
Check and close please.
Thanks.

**Comment by hectorerb** [comment]
Hi, @ajsb85 
We do not use Spaceship, we prefer to use fastlane and shell script for it. So yes, close you the issues

**Comment by ajsb85** [comment]
@hectorerb Hi.
Alexander Salas Bastidas:
Fastlane use a web wrapper for TestFlight instead to use the API in Spaceship.

**Comment by hectorerb** [comment]
@ajsb85 that's right, so we may to use Spaceship just for TestFlight and upload to App Store. with this change most of the CI / CD will be in ruby

**Comment by hectorerb** [comment]
@ajsb85 No problem with that?

**Comment by ajsb85** [comment]
No problem, and I need your help to create a nice plugin for @Aethonanbot and Spaceship
https://github.com/aethonanbot/fastlane-plugin-aethonan

**Comment by ajsb85** [comment]
Examples of notifications for @aethonanbot

🚢 Deploy was successful on Fastlane:

🚢 Deploy was successful on Spaceship:
