### ISSUE TITLE
XML of example

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/fusioninventory-ios#48]
Hi, @hectorerb 

I need to upload an example XML for iPad and iPod touch.
These will be used in the next section of the documentation page:

- [x] iPhone
- [x] iPad
- [ ] iPod Touch

![captura de pantalla 2017-08-23 a la s 6 02 00 p m](https://user-images.githubusercontent.com/19965590/29640505-3a420648-882d-11e7-9f48-190011e1c473.png)

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Could you test the inventory agent in your iPod touch to upload the XML generated?
Thanks.

**Comment by Naylin15** [comment]
I would gladly but my iPod is 4th generation and iOS 6.1

**Comment by ajsb85** [comment]
@Naylin15 Vale, tranquila. Gracias.
Voy a tratar de conseguir uno en Wallapop
