### ISSUE TITLE
Display function information

### ISSUE THREAD

**Issue by hectorerb** [flyve-mdm/fusioninventory-ios#64]
Hi, @Gianfranco97 

Could you review why the theme for jazzy does not display the information of the functions?

http://flyve.org/flyve-mdm-ios-inventory-agent/docs/Classes/AgentSettingsController.html

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 
Any update?

**Comment by Gianfranco97** [comment]
Yes, the error occurred because a javascript file was missing. I already solved this problem.
