### ISSUE TITLE
Privacy section

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/fusioninventory-ios#70]
Hi, @hectorerb 

The idea is create 2 new items with checkboxes in the Global Settings with the header: Privacy.

- [x] Health Report \ Send crash reports (Enable/ Disable bugsnag)
- [x] Usage Data \ Send anonymous usage data (Send copy of the inventory to inventory.flyve.org)

Thanks.

**Comment by rafaelje** [comment]
@ajsb85 Fine I understand
