### ISSUE TITLE
Transifex issues

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/fusioninventory-ios#89]
Hi, @hectorerb 

In Transifex, these issues were opened with the following information: 

File: Localizable.string

1. The original string should be "Flyve MDM Inventory Agent has restarted" instead of "Flyve MDM Inventory Agent is restarted".
1. The original string should be "FusionInventory Agent has restarted" instead of "FusionInventory Agent is restarted".
1. The original string "End of inventory." shouldn't ends up with dot (.); it should be "End of inventory".

Transifex links:

[Resource Localizable.string](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/localizablestrings/120539090)
[Resource Localizable.string](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/localizablestrings/120539082)
[Resource Agent](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/agent/115027041)
[Resource Agent](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/agent/115027000)
[Resource localizableplist-ios](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/localizableplist-ios/119132246)
[Resource localizableplist-ios](https://www.transifex.com/flyve-mdm/flyve-mdm-ios-inventory-agent/translate/#es_ES/localizableplist-ios/119132230)

**Comment by hectorerb** [comment]
Hi, @Naylin15 

The app only uses the Localizable.string resource.

**Comment by ajsb85** [comment]
@hectorerb You have admin access in the Transifex account, could you remove the other resources?

**Comment by hectorerb** [comment]
@ajsb85 done!
