### ISSUE TITLE
Shows incorrect version information...

### ISSUE THREAD

**Issue by tabad** [flyve-mdm/fusioninventory-ios#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Flyve Inventory Agent shows incorrect version information.

## Expected behavior

Flyve Inventory Agent shows correct version information.

## Minimal reproduction of the problem with instructions

In *Flyve Inventory Agent > About* the application shows `v`

![Inventory, version 0.1.0, build 235](https://user-images.githubusercontent.com/2183103/31757934-8421cf28-b4ab-11e7-8c1c-40d7f7ff8760.jpg)

but TestFlight shows `v`

![Version 0.2.0 (235)](https://user-images.githubusercontent.com/2183103/31757935-8447c016-b4ab-11e7-9630-8cd6b1591824.jpg)

## What is the motivation / use case for changing the behavior?

I think it's clear.

## Environment

I think the environment is this but...

<pre><code>
Inventory Agent Version: 0.2.0
</code></pre>

**Comment by ajsb85** [comment]
I confirm.

**Comment by ajsb85** [comment]
Hi,

With the last update notification today it's OK for me now.

![image](https://user-images.githubusercontent.com/663460/31776499-019de604-b4ec-11e7-9553-97b082d0c3b9.png)

![image](https://user-images.githubusercontent.com/663460/31776509-085078f4-b4ec-11e7-995e-ccb90d10b972.png)

**Comment by tabad** [comment]
Yes, you are right @ajsb85. Flyve MDM Inventory Agent for iOS v0.2.0 (build 259) doesn't have this problem.
